<Project>
  <!-- Shared version + product metadata for every project in the repo. -->
  <PropertyGroup>
    <Version>0.14.0</Version>
    <Authors>Lewis Barton</Authors>
    <Product>TCG Card Shop Sim Mod Manager</Product>
    <Company>Lewis Barton</Company>
    <Copyright>Copyright (c) 2026 Lewis Barton</Copyright>
  </PropertyGroup>
</Project>
